import Head from "next/head";
import Image from "next/image";
import PostList from "../components/PostList";
import styles from "../styles/Home.module.css";

export default function Home({posts}) {
  console.log(posts)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostList posts={posts}></PostList>
    </div>
  );
}

export const getStaticProps= async ()=>{
  const response = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=5')
  const posts = await response.json()
  return {
    props:{
      posts,
    }
  }
}